name: Update News with Sentiment Analysis

on: [push]
# on:
#   schedule:
#     - cron: "0 11 * * *" # KST 매일 03:00

permissions:
  contents: write

jobs:
  update-json:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13.5]

    steps:
      - uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # - name: Install python package
      #   run: |
      #     pip install -r requirements.txt

      - name: Run main.py
        run: |
          python test.py

      - name: Commit & Push
        run: |
          git config user.name "Dockerel"
          git config user.email "dgh0001@naver.com"
          git remote set-url origin https://github.com/invigoworks-knu/ai-news-sentiment-analysis.git
          git add -A
          git commit -m "chore: news with sentiment analyis updated" || echo "No changes to commit"
          git push https://x-access-token:$GITHUB_TOKEN@github.com/invigoworks-knu/ai-news-sentiment-analysis.git

